apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-shop-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mini-shop
  template:
    metadata:
      labels:
        app: mini-shop
    spec:
      containers:
        - name: mini-shop
          image: ghcr.io/stevver/mini-shop-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: BUILD
              value: "k3s"
